# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:            # Required
        # Examples:
        in_memory:
            memory:
                users:
                    florie:
                        password:           lulipooh
                        roles:              ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            pattern: "^/"
            http_basic: ~

    access_control:
        - { path: "^/", roles: ROLE_ADMIN }
